import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'antd/dist/reset.css'; // <-- Reset styles for Ant Design
import './globals.css';
import { ConfigProvider } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";

// Optional: load the same font via next/font
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <ConfigProvider
              theme={{
                token: {
                  colorPrimary: "#FFC300",         // your golden yellow
                  colorTextBase: "#000000",        // black text
                  fontFamily: inter.style.fontFamily,
                  borderRadius: 8,
                },
                // algorithm: antdTheme.defaultAlgorithm,
              }}
            >
            {children}
            </ConfigProvider>
      </body>
    </html>
  );
}
